name: Salesforce CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          echo "Y" | sfdx plugins:install salesforcedx
          sfdx auth:jwt:grant --clientid ${{ secrets.SFDC_CLIENT_ID }} --jwtkeyfile ${{ secrets.SFDC_JWT_KEY_FILE }} --username ${{ secrets.SFDC_USERNAME }} --setdefaultdevhubusername

      - name: Deploy to Scratch Org
        run: |
          sfdx force:source:deploy -u YourScratchOrgAlias -p force-app
